# Generated by Django 5.1.4 on 2024-12-26 17:42

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='due_date',
            field=models.DateField(default=cars.models.default_due_date),
        ),
    ]
