# Generated by Django 5.1.4 on 2024-12-26 18:20

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rental_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=cars.models.default_due_date),
        ),
    ]
