# Generated by Django 5.1.4 on 2024-12-26 18:32

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_rental_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='due_date',
            field=models.DateTimeField(blank=True, default=cars.models.default_due_date, null=True),
        ),
    ]
